<script lang="ts">
	import { onMount } from 'svelte';
	import { writable } from 'svelte/store';
	import { turnstile } from '@svelte-put/cloudflare-turnstile';

	// Stores
	const urlSubmit = writable('https://test.com');
	const message = writable('');
	const error = writable('');
	const darkMode = writable(false);
	const timestamp = writable(new Date().toLocaleString());
	const aimodel = 'OpenAI GPT-4';
	let tokenSubmit = $state('non');

	const send = async () => {
		message.set('');
		error.set('');
		alert(tokenSubmit);
		if (!$urlSubmit.startsWith('https://')) {
			error.set('Invalid URL');
			return;
		}

		const body = { url: urlSubmit, token: tokenSubmit };
		try {
			const response = await fetch('https://api.toxicpeople.org/0/add', {
				body: JSON.stringify(body),
				method: 'POST',
				headers: { 'Content-Type': 'application/json' }
			});
			const data = await response.json();

			//@ts-ignore
			if (data.status === 'OK') {
				message.set('Thank you');
			} else {
				error.set('Not accepted');
			}
		} catch (err) {
			error.set('Network error');
		}
	};

	// Sample Data
	const toxicPeople = [
		{ rank: 1, name: 'John Doe', country: 'USA', percentage: '92%' },
		{ rank: 2, name: 'Jane Smith', country: 'UK', percentage: '89%' },
		{ rank: 3, name: 'Ivan Petrov', country: 'Russia', percentage: '85%' },
		{ rank: 4, name: 'Carlos Gómez', country: 'Mexico', percentage: '80%' },
		{ rank: 5, name: 'Chen Wei', country: 'China', percentage: '75%' },
		{ rank: 6, name: 'John Doe', country: 'USA', percentage: '92%' },
		{ rank: 7, name: 'Jane Smith', country: 'UK', percentage: '89%' },
		{ rank: 8, name: 'Ivan Petrov', country: 'Russia', percentage: '85%' },
		{ rank: 9, name: 'Carlos Gómez', country: 'Mexico', percentage: '80%' },
		{ rank: 10, name: 'Chen Wei', country: 'China', percentage: '75%' }
	];

	// Initialize dark mode
	onMount(() => {
		const savedDarkMode = localStorage.getItem('darkMode') === 'true';
		darkMode.set(savedDarkMode);
		document.documentElement.classList.toggle('dark', savedDarkMode);

		//@ts-ignore
		turnstile.render('#cf-turnstile', {
			sitekey: '0x4AAAAAAA9xb3JXc6U5zRsDS9ft_I3UA88',
			callback: function (token: string) {
				tokenSubmit = token;
				alert(token);
				console.log(`Challenge Success ${token}`);
			}
		});
		alert('mounted');
	});

	// Toggle Dark Mode
	function toggleDarkMode() {
		darkMode.update((d) => {
			const newValue = !d;
			document.documentElement.classList.toggle('dark', newValue);
			localStorage.setItem('darkMode', newValue.toString());
			return newValue;
		});
	}
</script>

<div class="container">
	<button class="toggle" onclick={toggleDarkMode}>Toggle Dark Mode</button>
	<h1 class="title">Toxic People</h1>
	<table>
		<thead>
			<tr>
				<th>Rank</th>
				<th>Name</th>
				<th>Country</th>
				<th>Percentage</th>
			</tr>
		</thead>
		<tbody>
			{#each toxicPeople as person}
				<tr>
					<td>{person.rank}</td>
					<td>{person.name}</td>
					<td>{person.country}</td>
					<td>{person.percentage}</td>
				</tr>
			{/each}
		</tbody>
	</table>

	<p class="timestamp">Generated: {$timestamp}</p>

	<p>Toxicity rating process is fully automated without any human intervention.</p>
	<p>Everything on this site is auto-generated by AI, model today: <b>{aimodel}</b></p>

	<div>
		<label for="url-input">Add:</label>
		<input id="url-input" type="text" placeholder="https://" bind:value={$urlSubmit} />
		<button onclick={send} type="button">Add</button>
	</div>

	<!-- Cloudflare Turnstile -->
	<div
		use:turnstile
		turnstile-sitekey="0x4AAAAAAA9xb9K_rz-7bF0t"
		turnstile-theme="dark"
		turnstile-size="normal"
		turnstile-language="en"
		turnstile-response-field-name="turnstile"
		turnstile-response-field
		onturnstile={(e) => (tokenSubmit = e.detail.token)}
	></div>

	<p class="message">{$message}</p>
	<p class="error">{$error}</p>
	<br />
	<div class="ref">
		Open Source project (MIT License) can be found on GitHub. Contact us at:<br />
		<a href="https://github.com/toxic-people">github.com/toxic-people</a>
	</div>
</div>

<style>
	:global(:root) {
		--bg-color: white;
		--text-color: black;
		--th-bg-color: #444;
	}

	:global(html.dark) {
		--bg-color: #121212;
		--text-color: white;
		--th-bg-color: #222;
	}

	:global(body) {
		background-color: var(--bg-color);
		color: var(--text-color);
		font-family: Arial, sans-serif;
		transition:
			background-color 0.3s,
			color 0.3s;
		margin: 0;
		padding: 0;
	}

	.container {
		max-width: 600px;
		margin: 30px auto;
		text-align: center;
	}

	table {
		width: 100%;
		border-collapse: collapse;
		margin-top: 20px;
	}

	th,
	td {
		border: 1px solid #ddd;
		padding: 8px;
		text-align: center;
	}

	th {
		background: var(--th-bg-color);
		color: white;
	}

	a {
		color: #777777;
		text-decoration: none;
	}

	.toggle {
		margin: 20px;
		padding: 10px 20px;
		border: none;
		cursor: pointer;
		background: var(--th-bg-color);
		color: white;
		border-radius: 5px;
	}

	.message {
		color: green;
	}

	.error {
		color: red;
	}

	.ref {
		font-size: 11px;
	}

	.timestamp {
		font-size: 11px;
		font-family: 'Courier New', Courier, monospace, sans-serif;
	}

	.title {
		font-size: 50px;
	}
</style>
