<script lang="ts">
	import { onMount } from 'svelte';
	import { writable } from 'svelte/store';
	import { turnstile } from '@svelte-put/cloudflare-turnstile';
	import { Moon, Sun } from 'lucide-svelte';

	const message = writable('');
	const error = writable('');
	const darkMode = writable(false);
	var timestamp = writable(new Date().toLocaleString());
	const aimodel = 'OpenAI GPT-4';

	let tokenSubmit = $state('non');
	let urlSubmit = $state('');

	type People = {
		rank: number;
		name: string;
		country: string;
		wikipediaUrl: string;
	};

	type Render = {
		people: People[];
		created: number;
	};

	type Person = {
		rank: number;
		name: string;
		country: string;
		rating: number;
	};

	let toxicPeople: Array<People> = $state([]);

	const send = async () => {
		message.set('');
		error.set('');
		if (!urlSubmit.startsWith('https://')) {
			error.set('Invalid URL');
			return;
		}

		const body = { urlSubmit: urlSubmit, token: tokenSubmit };
		try {
			const response = await fetch('https://api.toxicpeople.org/0/add', {
				body: JSON.stringify(body),
				method: 'POST',
				headers: { 'Content-Type': 'application/json' }
			});
			const data = await response.json();

			//@ts-ignore
			if (data.status === 'OK') {
				message.set('Thank you');
			} else {
				error.set('Not accepted');
			}
		} catch (err) {
			error.set('Network error');
		}
	};

	// Initialize dark mode
	onMount(async () => {
		const uri = 'https://api.toxicpeople.org/0/get/MAIN_NEW';
		try {
			const response = await fetch(uri);
			if (!response.ok) {
				throw new Error(`Response status: ${response.status}`);
			}
			const render: Render = (await response.json()) as Render;
			toxicPeople = render.people;
			timestamp.set(new Date(render.created).toLocaleDateString());
		} catch (error) {
			//@ts-ignore
			console.error(error.message);
		}

		const savedDarkMode = localStorage.getItem('darkMode') === 'true';
		darkMode.set(savedDarkMode);
		document.documentElement.classList.toggle('dark', savedDarkMode);
	});

	// Toggle Dark Mode
	function toggleDarkMode() {
		darkMode.update((d) => {
			const newValue = !d;
			document.documentElement.classList.toggle('dark', newValue);
			localStorage.setItem('darkMode', newValue.toString());
			return newValue;
		});
	}
</script>

<div class="container">
	<div class="title">
		<img class="logo" src="/favicon.png" alt="logo" height="17" />&nbsp;&nbsp;Toxic People &nbsp;
		&nbsp; &nbsp;
		<div class="toggle">
			{#if $darkMode}<Moon onclick={toggleDarkMode} size={15} />{/if}
			{#if !$darkMode}<Sun onclick={toggleDarkMode} size={15} />{/if}
		</div>
	</div>
	<div class="teaser">
		<img class="finger" src="/handL.png" alt="finger" height="20" />&nbsp; Entfant Terribles of the
		Internet: Fearless or just Toxic?&nbsp;
		<img class="finger" src="/hand.png" alt="finger" height="20" />
		&nbsp;&nbsp;&nbsp;
	</div>
	<br />
	<table>
		<thead>
			<tr>
				<th>Rank</th>
				<th>Name</th>
				<th>Country</th>
				<!--<th>Percentage</th>-->
			</tr>
		</thead>
		<tbody>
			{#each toxicPeople as person}
				<tr>
					<td>{person.rank}</td>
					<td><a target="_blank" href={person.wikipediaUrl}>{person.name}</a></td>
					<td>{person.country}</td>
					<!---<td>{person.rating}</td>>-->
				</tr>
			{/each}
		</tbody>
	</table>
	<br />
	<p class="timestamp">AI generated: {$timestamp}</p>

	<p class="desc">Toxicity rating process is fully automated without any human intervention.</p>
	<p class="desc">
		The expressed rating is the AI model's perspective of the people's on-line behaviour.
	</p>
	<p class="desc">
		Everything on this site is auto-generated by AI, model in use: <b class="model">{aimodel}</b>
	</p>

	<div>
		<input class="link" id="url-input" type="text" placeholder="https://" bind:value={urlSubmit} />
		<button class=" blue" onclick={send} type="button">Add</button>
	</div>

	<br />
	<!-- Cloudflare Turnstile -->
	<div
		use:turnstile
		turnstile-sitekey="0x4AAAAAAA9xb9K_rz-7bF0t"
		turnstile-theme="dark"
		turnstile-size="normal"
		turnstile-language="en"
		turnstile-response-field-name="turnstile"
		turnstile-response-field
		onturnstile={(e) => (tokenSubmit = e.detail.token)}
	></div>

	<p class="message">{$message}</p>
	<p class="error">{$error}</p>
	<br />
	<div class="ref">
		Open Source project (MIT License) can be found on GitHub. Contact us at:<br />
		<a href="https://github.com/toxic-people">github.com/toxic-people</a>
	</div>
</div>

<style>
	@import url('https://fonts.googleapis.com/css2?family=Jockey+One&family=Roboto:ital,wght@0,100..900;1,100..900&display=swap');

	.blue {
		position: relative;
		top: 1px;
		background-color: rgb(3, 150, 240);
		color: white;
		width: 80px;
		height: 25px;
		display: inline-block;
		font-size: 14px;
		border-radius: 8px;
	}
	.logo {
		border-radius: 8px;
	}
	.model {
		color: white;
	}
	.link {
		width: 220px;
	}
	.desc {
		color: orange;
	}
	.finger {
		position: relative;
		top: 12px;
	}
	.title {
		display: flex;
		justify-content: center;
		align-self: center;
		color: yellowgreen;
		font-size: 35px;
		font-family: 'Jockey One', serif;
		font-weight: 400;
	}
	.teaser {
		display: flex;
		justify-content: center;
		align-self: center;
		color: orange;
		font-size: 18px;
		font-family: 'Roboto', serif;
		font-weight: 300;
	}
	:global(:root) {
		--bg-color: white;
		--text-color: black;
		--th-bg-color: #444;
	}

	:global(html.dark) {
		--bg-color: #121212;
		--text-color: white;
		--th-bg-color: #222;
	}

	:global(body) {
		background-color: var(--bg-color);
		color: var(--text-color);
		font-family: Arial, sans-serif;
		transition:
			background-color 0.3s,
			color 0.3s;
		margin: 0;
		padding: 0;
	}

	.container {
		max-width: 600px;
		margin: 30px auto;
		text-align: center;
	}

	table {
		width: 100%;
		border-collapse: collapse;
		margin-top: 20px;
	}

	th,
	td {
		border: 1px solid #ddd;
		padding: 8px;
		text-align: center;
	}

	th {
		background: var(--th-bg-color);
		color: white;
	}

	a {
		text-decoration: none;
		color: var(--text-color);
	}

	.toggle {
		position: relative;
		color: gray;
	}

	.message {
		color: green;
	}

	.error {
		color: red;
	}

	.ref {
		font-size: 11px;
	}

	.timestamp {
		font-size: 11px;
		font-family: 'Courier New', Courier, monospace, sans-serif;
	}
</style>
